---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingressHost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-redis
            port:
              number: 6379

