---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rollouts-demo-primary
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingressHost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rollouts-demo-primary
            port:
              number: 80
